pipeline:
  identifier: Build_delegate_template_1698688539993
  name: Build delegate-template
  orgIdentifier: default
  projectIdentifier: testproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: bharatgoelharness/delegate-template
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    connectorRef: account.harnessImage
                    image: nginx
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: smpistio
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
